---
services:
  main:
    image: docker.io/dmotte/svcbox:latest
    build: build
    restart: always
    ports:
      # - "2222:22" # If running supervisord as root
      - "2222:2222" # If running supervisord as unprivileged user
    volumes:
      # - ./sshset-data-root:/opt/sshset/data # If running supervisord as root
      - ./sshset-data-unpriv:/opt/sshset/data # If running supervisord as unprivileged user
      # Custom logs processing logic
      - ./logtosupd-process.py:/usr/local/lib/python3.13/dist-packages/logtosupd/process.py:ro
    environment:
      USERNGO_NAME: myuser
      USERNGO_SUDOER: "true"
      USERNGO_NOPASSWD: "true"
      SVCBOX_SUPERVISORCTL: "true"
